Added options "headings" and "class"
afeld/bootstrap-toc pull request #26
Opened 2016-10-17 07:02 UTC by Ircama

**Added options "headings" and "class"**

Congratulations for this plugin and thanks!

This PR would like to contribute by adding the following options:

 * headings
 * class

Example [here](https://ircama.github.io/osm-carto-tutorials/tile-server-ubuntu/) (unfinished document at the time of writing).

I also updated index.md (the documentation) and I set the version to "0.4.2".

Feel free to revise the code as you like.

Notice that with this PR tests and CDN are not updated.

 Changes to be committed:
	modified:   bootstrap-toc.js
	modified:   dist/bootstrap-toc.js
	modified:   dist/bootstrap-toc.min.js
	modified:   index.md
	modified:   package.json

2016-10-24 03:56 UTC, afeld requested changes
Hey there! Thanks for submitting. Left some comments inline. While I would be happy to merge some parts of the changes (the description of the search logic and the automatic addition of class names), I'm less sure about the new options. Also, just added some [contributor guidelines](https://github.com/afeld/bootstrap-toc/blob/gh-pages/CONTRIBUTING.md)—even though it's after the fact, mind giving them a read and updating accordingly? Thanks again!

2016-10-24 03:56 UTC, afeld commented on index.md
> +```
Let's use the existing [options](https://afeld.github.io/bootstrap-toc/#options) object—no need to make a second one.

2016-10-24 03:56 UTC, afeld commented on index.md
> +By default, the plugin finds the first heading level (`<h1>`, then `<h2>`, etc.) that has more than one element and defaults to 1 (for `<h1>`). The identified level becomes the top heading and the pl
This is great, thanks for adding!

2016-10-24 03:56 UTC, afeld commented on index.md
> +* `headings` (which can be a string): if set to a list of headers (in the form *hN,hM,...* where N, M, ... are levels, e.g., `h1,h2,h3`), all of them are searched instead of the first declared one an
What's the use case here? Do you have an example page where you would want to use this? What would the desired outcome be? Also, does this differ from

``` javascript
$scope: $('h1,h2,h3,h4,h5,h6')
```

?

2016-10-24 03:56 UTC, afeld commented on index.md
> +* `class`: (which can be a string): if set to a string, its value is used to customize the CSS class that the plugin sets for each description, concatenating it with the related header level. If not
While I like the adding of classes to different levels to make styling easier, the customization of said class seems overkill...

2016-10-24 03:56 UTC, afeld commented on index.md
> +}
Mind removing the `try`/`catch`? Using it like this would swallow _any_ errors, and therefore is definitely not something I want the documentation to encourage.

2016-10-24 03:56 UTC, afeld commented on bootstrap-toc.js
> + * - class
Mind removing this? If all contributions were added to the top of the file, it would get very large very fast 😏  Easier to point people to

https://github.com/afeld/bootstrap-toc/search?q=-author%3Aafeld&type=Issues&utf8=%E2%9C%93

since that list keeps itself up-to-date.

2016-10-24 03:56 UTC, afeld commented on index.md
> +```
Thinking it would make more sense to throw an example like this in [a sandbox](https://advanced-js.github.io/syllabus/#htmlcssjs-sandboxes) so that it can be interactive, and tweakable by the user.

2016-10-24 03:56 UTC, afeld commented on index.md
> +* `class`: (which can be a string): if set to a string, its value is used to customize the CSS class that the plugin sets for each description, concatenating it with the related header level. If not
Also, what's the behavior when the top-level heading in the sidebar corresponds to an `<h2>`? My assumption is that users would care more about the level in the table of contents than what `h*` it corresponds to, so I would make it more clear by using `toc-nav-level-1` and `toc-nav-level-2` or something like that.

2016-10-24 06:31 UTC, Ircama commented on index.md
> +* `headings` (which can be a string): if set to a list of headers (in the form *hN,hM,...* where N, M, ... are levels, e.g., `h1,h2,h3`), all of them are searched instead of the first declared one an
Hi, I generally agree about your comments and you can add new commits to this branch. This PR was more than discuss than considering an immediate merge.

> What's the use case here? Do you have an example page where you would want to use this? What would the desired outcome be?

Check this page as an example:

https://ircama.github.io/osm-carto-tutorials/tile-server-ubuntu/

Your plugin is running there.

In fact, at the end of the HTML:

```javascript
  $(function() {
    var navSelector = '#toc';
    var $myNav = $(navSelector);
    Toc.init($myNav, { headings: 'h1,h2,h3,h4,h5,h6' } );
    $('body').scrollspy({
      target: navSelector,
      offset: 220
    });
  });
```

In the page, you can see that my top level is 2 and that I generally use one sublevel, but there are some paragraphs with an additional sublevel 4:

https://ircama.github.io/osm-carto-tutorials/tile-server-ubuntu/#install-mapnik-library-from-package

* [h2] Install Mapnik library
  * [h3] Install Mapnik library from package
  * [h3] Alternatively, install Mapnik from sources
    * [h4] Install Boost from package
    * [h4] Alternatively, install the latest version of Boost from source
    * [h4] Install HarfBuzz from source
    * [h4] Build the Mapnik library from source

You see that h4 items are present (this is thanks to `{ headings: 'h1,h2,h3,h4,h5,h6' }`), are jointly expanded with h3 (and there is no way with this drop to do differently) and they are indented and represented with smaller font size (thanks to the auto-class naming and to the CSS).

> Also, does this differ from `$scope: $('h1,h2,h3,h4,h5,h6')`?

Could you please make an example of this?

2016-10-24 06:32 UTC, Ircama commented on index.md
> +* `headings` (which can be a string): if set to a list of headers (in the form *hN,hM,...* where N, M, ... are levels, e.g., `h1,h2,h3`), all of them are searched instead of the first declared one an
Hi, I generally agree about your comments and you can add new commits to this branch. This PR was more than discuss than considering an immediate merge.

> What's the use case here? Do you have an example page where you would want to use this? What would the desired outcome be?

Check this page as an example:

https://ircama.github.io/osm-carto-tutorials/tile-server-ubuntu/

Your plugin is running there.

In fact, at the end of the HTML:

```javascript
  $(function() {
    var navSelector = '#toc';
    var $myNav = $(navSelector);
    Toc.init($myNav, { headings: 'h1,h2,h3,h4,h5,h6' } );
    $('body').scrollspy({
      target: navSelector,
      offset: 220
    });
  });
```

In the page, you can see that my top level is 2 and that I generally use one sublevel, but there are some paragraphs with an additional sublevel 4:

https://ircama.github.io/osm-carto-tutorials/tile-server-ubuntu/#install-mapnik-library-from-package

* [h2] Install Mapnik library
  * [h3] Install Mapnik library from package
  * [h3] Alternatively, install Mapnik from sources
    * [h4] Install Boost from package
    * [h4] Alternatively, install the latest version of Boost from source
    * [h4] Install HarfBuzz from source
    * [h4] Build the Mapnik library from source

You see that h4 items are present (this is thanks to `{ headings: 'h1,h2,h3,h4,h5,h6' }`), are jointly expanded with h3 (and there is no way with this drop to do differently) and they are indented and represented with smaller font size (thanks to the auto-class naming and to the CSS).

> Also, does this differ from `$scope: $('h1,h2,h3,h4,h5,h6')`?

Could you please make an example of this?

2016-10-24 06:34 UTC, Ircama commented on index.md
> +By default, the plugin finds the first heading level (`<h1>`, then `<h2>`, etc.) that has more than one element and defaults to 1 (for `<h1>`). The identified level becomes the top heading and the pl
Hi, I generally agree about your comments and you can add new commits to this branch. This PR was more than discuss than considering an immediate merge.

> What's the use case here? Do you have an example page where you would want to use this? What would the desired outcome be?

Check this page as an example:

https://ircama.github.io/osm-carto-tutorials/tile-server-ubuntu/

Your plugin is running there.

In fact, at the end of the HTML:

```javascript
  $(function() {
    var navSelector = '#toc';
    var $myNav = $(navSelector);
    Toc.init($myNav, { headings: 'h1,h2,h3,h4,h5,h6' } );
    $('body').scrollspy({
      target: navSelector,
      offset: 220
    });
  });
```

In the page, you can see that my top level is 2 and that I generally use one sublevel, but there are some paragraphs with an additional sublevel 4:

https://ircama.github.io/osm-carto-tutorials/tile-server-ubuntu/#install-mapnik-library-from-package

* [h2] Install Mapnik library
  * [h3] Install Mapnik library from package
  * [h3] Alternatively, install Mapnik from sources
    * [h4] Install Boost from package
    * [h4] Alternatively, install the latest version of Boost from source
    * [h4] Install HarfBuzz from source
    * [h4] Build the Mapnik library from source

You see that h4 items are present (this is thanks to `{ headings: 'h1,h2,h3,h4,h5,h6' }`), are jointly expanded with h3 (and there is no way with this drop to do differently) and they are indented and represented with smaller font size (thanks to the auto-class naming and to the CSS).

> Also, does this differ from `$scope: $('h1,h2,h3,h4,h5,h6')`?

Could you please make an example of this?

2016-10-24 06:46 UTC, Ircama commented on index.md
> +* `class`: (which can be a string): if set to a string, its value is used to customize the CSS class that the plugin sets for each description, concatenating it with the related header level. If not
> While I like the adding of classes to different levels to make styling easier, the customization of said class seems overkill...

Maybe it is indead an overkill if no one is going to use the same root in other places. You can suggest a code rework or do it yourself if wanted.

> Also, what's the behavior when the top-level heading in the sidebar corresponds to an `<h2>`? My assumption is that users would care more about the level in the table of contents than what h* it corresponds to, so I would make it more clear by using toc-nav-level-1 and toc-nav-level-2 or something like that.

If you have top level h2, h1 in the middle of the document will be always shown when setting `headings: 'h1,h2,h3,h4,h5,h6'`, but not shown if leaving this option out.

> so I would make it more clear by using toc-nav-level-1 and toc-nav-level-2 or something like that.

To make sure I got your point, would you change `toc-nav-h` to `toc-nav-level-h`?

2016-10-24 06:47 UTC, Ircama commented on index.md
> +```
OK. Would you please suggest a code rework? Thanks

2016-10-24 06:48 UTC, Ircama commented on index.md
> +}
Yes, right!

2016-10-24 06:51 UTC, Ircama commented on index.md
> +```
Yes, that would be great, I did not have time to setup it.

2016-10-24 06:53 UTC, Ircama commented on bootstrap-toc.js
> + * - class
OK, sure!

2019-01-09 05:07 UTC, afeld reviewed
So sorry it took me so long to get back to this. Pulled the documentation additions out in #51 - going to close the rest as stale, but feel free to respond here or open new (smaller) issues / pull requests if still interested. Thanks!

2019-01-09 05:07 UTC, afeld commented on index.md
> +* `headings` (which can be a string): if set to a list of headers (in the form *hN,hM,...* where N, M, ... are levels, e.g., `h1,h2,h3`), all of them are searched instead of the first declared one an
Let's deal with the "depth" feature request separately: #37

2019-01-09 05:07 UTC, afeld commented on index.md
> +```
```javascript
Toc.init({
  $nav: $myNav,
  headings: 'h1,h2,h3,h4,h5,h6',
  class: 'my-class'
});
```

2019-01-09 05:07 UTC, afeld commented on index.md
> +* `class`: (which can be a string): if set to a string, its value is used to customize the CSS class that the plugin sets for each description, concatenating it with the related header level. If not
Still not sure I understand the use case here. Feel free to open an issue if you are still interested.

2019-01-09 05:07 UTC, closed without merging